import type { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const audioFormatOptions: INodePropertyOptions[] = [
	{ name: 'PCM 8000', value: 'pcm_8000' },
	{ name: 'PCM 16000', value: 'pcm_16000' },
	{ name: 'PCM 22050', value: 'pcm_22050' },
	{ name: 'PCM 24000', value: 'pcm_24000' },
	{ name: 'PCM 44100', value: 'pcm_44100' },
	{ name: 'PCM 48000', value: 'pcm_48000' },
	{ name: 'ULAW 8000', value: 'ulaw_8000' },
];

const assistantOptionalFields: INodeProperties[] = [
	{
		displayName: 'Assistant Output Audio Format',
		name: 'assistantOutputAudioFormat',
		type: 'options',
		options: audioFormatOptions,
		default: 'pcm_16000',
		description: 'Audio format of the assistant voice output',
		routing: { send: { type: 'body', property: 'assistantOutputAudioFormat' } },
	},
	{
		displayName: 'Disable First Message Interruption',
		name: 'disableFirstMessageInterruption',
		type: 'boolean',
		default: false,
		description: 'Whether to disable interruption of the first message',
		routing: { send: { type: 'body', property: 'disableFirstMessageInterruption' } },
	},
	{
		displayName: 'Eagerness',
		name: 'eagerness',
		type: 'options',
		options: [
			{ name: 'Eager', value: 'eager' },
			{ name: 'Normal', value: 'normal' },
			{ name: 'Patient', value: 'patient' },
		],
		default: 'normal',
		description: 'How eagerly the assistant takes its turn in a conversation',
		routing: { send: { type: 'body', property: 'eagerness' } },
	},
	{
		displayName: 'ElevenLabs Voice ID',
		name: 'elevenLabsVoiceId',
		type: 'string',
		default: '',
		description: 'ElevenLabs voice identifier for speech synthesis',
		routing: { send: { type: 'body', property: 'elevenLabsVoiceId' } },
	},
	{
		displayName: 'First Message',
		name: 'firstMessage',
		type: 'string',
		default: '',
		description: 'Message the assistant says first when a conversation starts',
		routing: { send: { type: 'body', property: 'firstMessage' } },
	},
	{
		displayName: 'Language',
		name: 'language',
		type: 'string',
		default: '',
		description: 'Assistant language code, e.g. en or ru',
		routing: { send: { type: 'body', property: 'language' } },
	},
	{
		displayName: 'Provider ID',
		name: 'providerId',
		type: 'string',
		default: '',
		description: 'Provider ID for voice assistant integration',
		routing: { send: { type: 'body', property: 'providerId' } },
	},
	{
		displayName: 'Silence End Call Timeout',
		name: 'silenceEndCallTimeout',
		type: 'number',
		default: -1,
		description:
			'Seconds of silence after which the call ends automatically. -1 disables, maximum 7200.',
		routing: { send: { type: 'body', property: 'silenceEndCallTimeout' } },
	},
	{
		displayName: 'Soft Timeout',
		name: 'softTimeout',
		type: 'number',
		default: 0,
		description: 'Soft timeout in seconds before the soft timeout message is played',
		routing: { send: { type: 'body', property: 'softTimeout' } },
	},
	{
		displayName: 'Soft Timeout Message',
		name: 'softTimeoutMessage',
		type: 'string',
		default: '',
		description: 'Message played when the soft timeout is reached',
		routing: { send: { type: 'body', property: 'softTimeoutMessage' } },
	},
	{
		displayName: 'Streaming Latency',
		name: 'streamingLatency',
		type: 'number',
		typeOptions: { minValue: 0, maxValue: 4 },
		default: 0,
		description: 'Streaming latency optimization (0-4)',
		routing: { send: { type: 'body', property: 'streamingLatency' } },
	},
	{
		displayName: 'Text LLM Model ID',
		name: 'textLlmModelId',
		type: 'string',
		default: '',
		description: 'LLM model ID used for text chats',
		routing: { send: { type: 'body', property: 'textLlmModelId' } },
	},
	{
		displayName: 'TTS Model',
		name: 'ttsModel',
		type: 'string',
		default: '',
		description: 'Text-to-speech model name',
		routing: { send: { type: 'body', property: 'ttsModel' } },
	},
	{
		displayName: 'Turn After Silence',
		name: 'turnAfterSilence',
		type: 'number',
		default: -1,
		description:
			'Max seconds since the user last spoke before the agent forces a turn. -1 waits indefinitely.',
		routing: { send: { type: 'body', property: 'turnAfterSilence' } },
	},
	{
		displayName: 'User Input Audio Format',
		name: 'userInputAudioFormat',
		type: 'options',
		options: audioFormatOptions,
		default: 'pcm_16000',
		description: 'Audio format of the user voice input',
		routing: { send: { type: 'body', property: 'userInputAudioFormat' } },
	},
	{
		displayName: 'VA Voice',
		name: 'vaVoice',
		type: 'string',
		default: '',
		description: 'Voice assistant voice name',
		routing: { send: { type: 'body', property: 'vaVoice' } },
	},
	{
		displayName: 'Voice Assistant ID',
		name: 'voiceAssistantId',
		type: 'string',
		default: '',
		description: 'External voice assistant identifier',
		routing: { send: { type: 'body', property: 'voiceAssistantId' } },
	},
	{
		displayName: 'Voice LLM Model ID',
		name: 'voiceLlmModelId',
		type: 'string',
		default: '',
		description: 'LLM model ID used for voice calls',
		routing: { send: { type: 'body', property: 'voiceLlmModelId' } },
	},
];

export const assistantOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['assistant'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create an assistant',
				routing: { request: { method: 'POST', url: '/api/assistants' } },
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete an assistant',
				routing: {
					request: { method: 'DELETE', url: '=/api/assistants/{{$parameter.assistantId}}' },
				},
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get an assistant',
				routing: {
					request: { method: 'GET', url: '=/api/assistants/{{$parameter.assistantId}}' },
				},
			},
			{
				name: 'Get Many',
				value: 'getMany',
				action: 'Get many assistants',
				routing: {
					request: { method: 'GET', url: '/api/assistants' },
					send: { paginate: '={{ $parameter.returnAll }}' },
					operations: {
						pagination: {
							type: 'offset',
							properties: {
								limitParameter: 'take',
								offsetParameter: 'skip',
								pageSize: 100,
								type: 'query',
							},
						},
					},
				},
			},
			{
				name: 'Originate Call',
				value: 'originateCall',
				action: 'Start an outgoing call',
				routing: {
					request: {
						method: 'POST',
						url: '=/api/assistants/{{$parameter.assistantId}}/originate',
					},
				},
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update an assistant',
				routing: {
					request: { method: 'PATCH', url: '=/api/assistants/{{$parameter.assistantId}}' },
				},
			},
		],
		default: 'getMany',
	},
];

export const assistantFields: INodeProperties[] = [
	{
		displayName: 'Assistant Name or ID',
		name: 'assistantId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getAssistants' },
		required: true,
		default: '',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: {
			show: { resource: ['assistant'], operation: ['delete', 'get', 'originateCall', 'update'] },
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of the assistant',
		displayOptions: { show: { resource: ['assistant'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Prompt Text',
		name: 'promptText',
		type: 'string',
		typeOptions: { rows: 4 },
		required: true,
		default: '',
		description: 'System prompt that defines the assistant behavior',
		displayOptions: { show: { resource: ['assistant'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'promptText' } },
	},
	{
		displayName: 'Company Name or ID',
		name: 'companyId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getCompanies' },
		required: true,
		default: '',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: { show: { resource: ['assistant'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'companyId' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['assistant'], operation: ['create'] } },
		options: assistantOptionalFields,
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['assistant'], operation: ['update'] } },
		options: [
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Name of the assistant',
				routing: { send: { type: 'body', property: 'name' } },
			},
			{
				displayName: 'Prompt Text',
				name: 'promptText',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'System prompt that defines the assistant behavior',
				routing: { send: { type: 'body', property: 'promptText' } },
			},
			...assistantOptionalFields,
		],
	},
	{
		displayName: 'Phone Number',
		name: 'phoneNumber',
		type: 'string',
		required: true,
		default: '',
		description:
			'Phone number to call: +&lt;digits&gt;, digits with country code (380...), or local format starting with 0',
		displayOptions: { show: { resource: ['assistant'], operation: ['originateCall'] } },
		routing: { send: { type: 'body', property: 'phoneNumber' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['assistant'], operation: ['originateCall'] } },
		options: [
			{
				displayName: 'Caller Assistant Name or ID',
				name: 'callerAssistantId',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getAssistants' },
				default: '',
				description: 'Assistant to make the call as (must belong to the same company). If omitted, the route assistant is used. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
				routing: { send: { type: 'body', property: 'callerAssistantId' } },
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['assistant'], operation: ['getMany'] } },
		options: [
			{
				displayName: 'Company Name or ID',
				name: 'companyId',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getCompanies' },
				default: '',
				description:
					'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				routing: { send: { type: 'query', property: 'companyId' } },
			},
			{
				displayName: 'Folder ID',
				name: 'folderId',
				type: 'string',
				default: '',
				description: 'Filter by folder ID',
				routing: { send: { type: 'query', property: 'folderId' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Filter by assistant name',
				routing: { send: { type: 'query', property: 'name' } },
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Free-text search',
				routing: { send: { type: 'query', property: 'search' } },
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{ name: 'Hybrid', value: 'hybrid' },
					{ name: 'Text', value: 'text' },
					{ name: 'Voice', value: 'voice' },
				],
				default: 'text',
				description: 'Filter by assistant type',
				routing: { send: { type: 'query', property: 'type' } },
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['assistant'], operation: ['getMany'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: { resource: ['assistant'], operation: ['getMany'], returnAll: [false] },
		},
		routing: { send: { type: 'query', property: 'take' } },
	},
	{
		displayName: 'Skip',
		name: 'skip',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Number of results to skip from the start',
		displayOptions: {
			show: { resource: ['assistant'], operation: ['getMany'], returnAll: [false] },
		},
		routing: { send: { type: 'query', property: 'skip' } },
	},
];
